jobs:
- job: CashtestSecurityScan
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: bash start_crashtest_azure.sh $CRASHTEST_WEBHOOK
    env:
      CRASHTEST_WEBHOOK: $(crashtestWebhook)
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test-reports/*.xml'