# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  # Declare a dependency on the heroku orb
  heroku: circleci/heroku@0.0.8

jobs:
  sast:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
            pipenv install safety
      - run:
          command: |
            pipenv run safety check --file requirements.txt --full-report
  dast:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          command: sh start_crashtest_circleci.sh $CRASHTEST_WEBHOOK
      - store_test_results:
          path: ~/crashtest

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
          force: true

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  workflow:
    jobs:
      - deploy
      - sast
